version: '3'

services:
  next-app:
    container_name: next
    build:
      dockerfile: Dockerfile

    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./sqlite.db:/app/sqlite.db
    restart: always
    ports:
      - 3000:3000
    networks:
      - codenames_annihilator_network

networks:
  codenames_annihilator_network:
    external: true
