import { Link } from '@components/ui/link'
import { routes } from '@utils/routes.utils'

export default function TermsOfServicePage(): React.ReactElement {
  return (
    <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8">
      <div className="flex justify-center">
        <article className="prose sm:prose-lg">
          <h2>Terms of Service</h2>
          <p>
            Welcome to Codenames Annihilator! These Terms of Service ("Terms")
            govern your use of our website located at{' '}
            <Link variant="underline" href={routes.root()}>
              codenames-annihilator.vercel.app
            </Link>{' '}
            (the "Site") and any related services provided by us. Please read
            these Terms carefully before using our services.
          </p>
          <p>
            By accessing or using the Site, you agree to be bound by these Terms
            and our Privacy Policy. If you do not agree to these Terms or our
            Privacy Policy, you may not access or use the Site.
          </p>

          <h3>Accounts</h3>
          <p>
            When you create an account with us, you must provide us with
            accurate, complete, and up-to-date information. Failure to do so
            constitutes a breach of these Terms, which may result in immediate
            termination of your account on our Service.
          </p>
          <p>
            You are responsible for safeguarding the password that you use to
            access the Service and for any activities or actions under your
            password, whether your password is with our Service or a third-party
            service.
          </p>

          <h3>Intellectual Property</h3>
          <p>
            The Service and its original content, features, and functionality
            are and will remain the exclusive property of Codenames Annihilator
            and its licensors. The Service is protected by copyright, trademark,
            and other laws of both the United States and foreign countries. Our
            trademarks and trade dress may not be used in connection with any
            product or service without the prior written consent of Codenames
            Annihilator.
          </p>

          <h3>Links To Other Web Sites</h3>
          <p>
            Our Service may contain links to third-party web sites or services
            that are not owned or controlled by Codenames Annihilator.
          </p>
          <p>
            Codenames Annihilator has no control over, and assumes no
            responsibility for, the content, privacy policies, or practices of
            any third-party web sites or services. You further acknowledge and
            agree that Codenames Annihilator shall not be responsible or liable,
            directly or indirectly, for any damage or loss caused or alleged to
            be caused by or in connection with use of or reliance on any such
            content, goods, or services available on or through any such web
            sites or services.
          </p>

          <h3>Termination</h3>
          <p>
            We may terminate or suspend your account and bar access to the
            Service immediately, without prior notice or liability, under our
            sole discretion, for any reason whatsoever and without limitation,
            including but not limited to a breach of the Terms.
          </p>
          <p>
            If you wish to terminate your account, you may simply discontinue
            using the Service.
          </p>

          <h3>Governing Law</h3>
          <p>
            These Terms shall be governed and construed in accordance with the
            laws of the United States, without regard to its conflict of law
            provisions.
          </p>

          <h3>Changes</h3>
          <p>
            We reserve the right, at our sole discretion, to modify or replace
            these Terms at any time. If a revision is material, we will provide
            at least 30 days' notice prior to any new terms taking effect. What
            constitutes a material change will be determined at our sole
            discretion.
          </p>
          <p>
            By continuing to access or use our Service after any revisions
            become effective, you agree to be bound by the revised terms. If you
            do not agree to the new terms, you are no longer authorized to use
            the Service.
          </p>

          <h3>Contact Us</h3>
          <p>If you have any questions about these Terms, please contact us.</p>
          <p>
            Finally, these terms of service are not real, they were generated by
            ChatGPT. Please don't take them seriously.
          </p>
        </article>
      </div>
    </div>
  )
}
