name: Lint & deploy preview

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install vercel CLI
        run: bun add --global vercel@latest

      - name: Pull vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull env vars from vercel
        run: vercel env pull --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run prettier and eslint
        run: bun lint

      - name: Update DB schema
        run: bun db:push

      - name: Build
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        id: deploy
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > URL
          PREVIEW_URL=$(<URL)
          echo "PREVIEW_URL=$PREVIEW_URL" >> "$GITHUB_OUTPUT"

      - name: Create comment with preview URL
        uses: mshick/add-pr-comment@v2
        env:
          PREVIEW_URL: ${{ steps.deploy.outputs.PREVIEW_URL }}
        with:
          message: 'Preview URL: ${{ env.PREVIEW_URL }}'
